name: CI/CD Apprentice 1
run-name: Build
on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types: [completed]
jobs:
  Build:
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
          npm run build
      - name: Output downloadable build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
      - run: |
          echo "🍏 This job's status is ${{ job.status }}."
          echo "The build is now ready for download from the Artifacts section"
